### ISSUE TITLE
Fix Issue with Tags/Releases

### ISSUE THREAD

**Issue by fullerzz** [fullerzz/borgboi#49]
After creating the tag `v1.0.0` and a release associated with that tag also called `v1.0.0`, commitizen created a tag `1.0.0` and release `1.0.0`.

Expected behavior: `cz` uses v1.0.0 and recognized that a tag and release for this version already exist

**Comment by fullerzz** [comment]
https://commitizen-tools.github.io/commitizen/commands/bump/#tag_format

Might need to update the tag format to:

```toml
[tool.commitizen]
tag_format = "v$major.$minor.$patch$prerelease"
```
